In [1]:
import pandas as pd

In [2]:
path_plants = "https://raw.githubusercontent.com/dataforgoodfr/batch7_satellite_ges/master/dataset/CO2_emissions_centrale.csv"

plants = pd.read_csv(path_plants, sep=",", index_col=0)

plants.head()

,country_long,capacity_mw,latitude,longitude,primary_fuel,generation_gwh_2013,generation_gwh_2014,generation_gwh_2015,generation_gwh_2016,generation_gwh_2017,estimated_generation_gwh,gCO2/KWh,generation_gwh_2017_with_estimated_data,tCO2_emitted_in_2013,tCO2_emitted_in_2014,tCO2_emitted_in_2015,tCO2_emitted_in_2016,tCO2_emitted_in_2017,tCO2_emitted_in_2017_with estimated_data
0,Afghanistan,42.0,34.5638,69.1134,Gas,NaN,NaN,NaN,NaN,NaN,NaN,443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Algeria,520.0,35.8665,6.0262,Gas,NaN,NaN,NaN,NaN,NaN,2152.249819,443,2152.249819,NaN,NaN,NaN,NaN,NaN,9.534467e+05
2,Algeria,71.0,36.8924,7.7634,Gas,NaN,NaN,NaN,NaN,NaN,293.864879,443,293.864879,NaN,NaN,NaN,NaN,NaN,1.301821e+05
3,Algeria,560.0,36.5988,3.1375,Gas,NaN,NaN,NaN,NaN,NaN,2317.807497,443,2317.807497,NaN,NaN,NaN,NaN,NaN,1.026789e+06
4,Algeria,100.0,36.5914,2.9223,Gas,NaN,NaN,NaN,NaN,NaN,413.894196,443,413.894196,NaN,NaN,NaN,NaN,NaN,1.833551e+05

In [3]:
data = pd.read_csv("https://courty.fr/OCO2/result_for_oco2_1808.csv", sep=",", index_col=0)

data.head()

,sounding_id,latitude,longitude,orbit,slope,intercept,amplitude,sigma,delta,R,windspeed_u,windspeed_v
0,2018080101035604,25.425072,-177.345490,21709,0.000430,404.902899,-14.694226,-3.987167,1.470254,0.677812,-7.759225,-0.739198
1,2018080101060803,32.777554,-179.428162,21709,0.002886,404.622407,1.493849,7.887665,0.075556,0.532213,-5.420354,-0.992332
2,2018080101062035,33.441360,-179.630508,21709,-0.002734,404.470875,18.128640,3.086571,2.343144,-0.656713,-4.649583,-0.913302
3,2018080101062937,33.919857,-179.779083,21709,-0.006755,404.416030,-11.847855,-3.346435,1.412432,0.592854,-4.035365,-0.879741
4,2018080102530302,58.858116,143.781662,21710,0.003719,399.445056,-0.018193,-5.552475,0.001307,0.730703,-3.837832,0.812698

We spot some negative sigma and amplitude parameters.

In [4]:
data['sigma'] = data['sigma'].apply(abs)
data['amplitude'] = data['amplitude'].apply(abs)
data.head(15)

,sounding_id,latitude,longitude,orbit,slope,intercept,amplitude,sigma,delta,R,windspeed_u,windspeed_v
0,2018080101035604,25.425072,-177.345490,21709,0.000430,404.902899,14.694226,3.987167,1.470254,0.677812,-7.759225,-0.739198
1,2018080101060803,32.777554,-179.428162,21709,0.002886,404.622407,1.493849,7.887665,0.075556,0.532213,-5.420354,-0.992332
2,2018080101062035,33.441360,-179.630508,21709,-0.002734,404.470875,18.128640,3.086571,2.343144,-0.656713,-4.649583,-0.913302
3,2018080101062937,33.919857,-179.779083,21709,-0.006755,404.416030,11.847855,3.346435,1.412432,0.592854,-4.035365,-0.879741
4,2018080102530302,58.858116,143.781662,21710,0.003719,399.445056,0.018193,5.552475,0.001307,0.730703,-3.837832,0.812698
5,2018080104244674,35.680077,130.219467,21711,-0.004196,405.367275,9.859749,24.716153,0.159146,0.577045,-2.515345,-1.818006
6,2018080104244836,35.752354,130.197632,21711,-0.004529,405.341883,7.635088,6.525770,0.466759,0.511861,-2.536525,-1.833167
7,2018080104244906,35.789249,130.185776,21711,-0.004221,405.311837,7.751707,9.587837,0.322542,0.533806,-2.545387,-1.840344
8,2018080104244976,35.826172,130.173950,21711,-0.003825,405.271937,9.293184,16.454924,0.225309,0.514400,-2.552335,-1.846606
9,2018080104245173,35.966625,130.125778,21711,-0.004961,405.187786,8.763453,17.915269,0.195147,0.616669,-2.563400,-1.864844
10,2018080104245475,36.112236,130.080261,21711,-0.005632,405.134489,5.867463,20.226835,0.115726,0.714837,-2.452534,-1.691839
11,2018080104245535,36.149014,130.068329,21711,-0.006073,405.120973,5.166552,11.382239,0.181085,0.597837,-2.414776,-1.631612
12,2018080104245738,36.229542,130.045258,21711,-0.006534,405.086223,3.223339,12.760039,0.100778,0.614451,-2.327447,-1.493044
13,2018080104245808,36.266342,130.033279,21711,-0.006272,405.075965,1.815272,10.704547,0.067652,0.518306,-2.286112,-1.427738
14,2018080104245938,36.339977,130.009537,21711,-0.006359,405.045625,0.299730,10.148986,0.011782,0.527084,-2.199892,-1.292075

In [5]:
data.describe()

,sounding_id,latitude,longitude,orbit,slope,intercept,amplitude,sigma,delta,R,windspeed_u,windspeed_v
count,2.739000e+03,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000,2739.000000
mean,2.018082e+15,20.739139,-2.252285,21942.401241,-0.001466,404.197221,15.786950,16.531691,0.404124,0.573809,-1.178559,-0.315456
std,9.332131e+08,26.381097,105.746297,135.804701,0.006618,1.975166,16.314918,6.898671,0.443052,0.193246,4.447457,3.729918
min,2.018080e+15,-40.021149,-179.779083,21709.000000,-0.031395,398.082968,0.003036,2.027053,0.000341,-0.772979,-9.672325,-9.554490
25%,2.018081e+15,-3.200449,-111.344830,21809.500000,-0.006007,402.793939,5.257624,11.223499,0.150471,0.531893,-4.771674,-3.273640
50%,2.018082e+15,29.949741,17.073837,21957.000000,-0.002799,404.515498,11.753573,15.898313,0.289059,0.575454,-1.931059,-0.296885
75%,2.018083e+15,40.669176,70.918045,22061.000000,0.003888,405.924259,20.856496,21.194157,0.498587,0.645554,2.321920,2.921310
max,2.018083e+15,72.424393,179.568573,22159.000000,0.025194,408.913894,162.436539,33.249874,5.603435,0.899008,13.551064,11.974917

To convert the  ``` sounding_id ``` into a datetime variable ```data```:

In [6]:
from datetime import datetime
def to_date(a):
    return datetime.strptime(str(a), '%Y%m%d%H%M%S%f')

data['date'] = data['sounding_id'].apply(to_date)
data.head()

,sounding_id,latitude,longitude,orbit,slope,intercept,amplitude,sigma,delta,R,windspeed_u,windspeed_v,date
0,2018080101035604,25.425072,-177.345490,21709,0.000430,404.902899,14.694226,3.987167,1.470254,0.677812,-7.759225,-0.739198,2018-08-01 01:03:56.040
1,2018080101060803,32.777554,-179.428162,21709,0.002886,404.622407,1.493849,7.887665,0.075556,0.532213,-5.420354,-0.992332,2018-08-01 01:06:08.030
2,2018080101062035,33.441360,-179.630508,21709,-0.002734,404.470875,18.128640,3.086571,2.343144,-0.656713,-4.649583,-0.913302,2018-08-01 01:06:20.350
3,2018080101062937,33.919857,-179.779083,21709,-0.006755,404.416030,11.847855,3.346435,1.412432,0.592854,-4.035365,-0.879741,2018-08-01 01:06:29.370
4,2018080102530302,58.858116,143.781662,21710,0.003719,399.445056,0.018193,5.552475,0.001307,0.730703,-3.837832,0.812698,2018-08-01 02:53:03.020

In [7]:
#!pip install folium

In [16]:
import folium
peaks_and_plants_dark = folium.Map([43, 0], zoom_start=4,tiles="CartoDB dark_matter")
input_dir = 'http://courty.fr/OCO2/'
for index, row in plants.iterrows():
    radius = 0.1
    color="#3186CC" # blue
    tooltip =  "["+str(round(row['latitude'],2))+" ; "+str(round(row['longitude'],2))+"]"
    emit = str(round(row['estimated_generation_gwh'],2))
    popup_html="""<h4>"""+tooltip+"""</h4>"""+row['country_long']+"""<p>Emission 2018 (est): """+emit+""" GWh</p>"""

    popup=folium.Popup(popup_html, max_width=450)

    folium.CircleMarker(location=(row["latitude"],
                                  row["longitude"]),
                        radius=radius,
                        color=color,
                        tooltip=tooltip,
                        popup=popup,
                        fill=True).add_to(peaks_and_plants_dark)

for index, row in data.iterrows():
#     if index> 300:
#         break
    radius = row["amplitude"]/20
    color="#E37222" # tangerine
    tooltip =  "["+str(round(row['latitude'],2))+" ; "+str(round(row['longitude'],2))+"]"
    sounding = str(row['sounding_id'])
    date = str(row['date'])
    orbit = str(row['orbit'])
    
    
    url = input_dir + "peak_data-si_"+sounding+".json"
    
    popup_html=f'<h4>{tooltip}</h4>{date}<p>sounding_id: {sounding}</br>orbit: {orbit}</p><p><a href="{url}" target="_new">Raw data</a></p>'
    slope, intercept, amplitude, sigma = str(row['slope']), str(row['intercept']), str(row['amplitude']), str(row['sigma'])
    popup_html+=f'<p><input type="button" value="Show plot" onclick="plot_data(\'{url}\', {slope}, {intercept}, {amplitude}, {sigma});"/></p>'
    #popup_html+=f'<script>plot_data(\'{url}\', {slope}, {intercept}, {amplitude}, {sigma});</script>'
    #  <input type="button" value="Click me" onclick="msg()"> 
    #popup_html="""<h4>"""+tooltip+"""</h4>"""+date+"""<p>sounding_id: """+sounding+"""</br>orbit: """+orbit+"""</p>"""

    popup=folium.Popup(popup_html, max_width=450)
    
    folium.CircleMarker(location=(row["latitude"],
                                  row["longitude"]),
                        radius=radius,
                        color=color,
                        tooltip=tooltip,
                        popup=popup,
                        fill=True).add_to(peaks_and_plants_dark)

#peaks_and_plants_dark

In [17]:
output_file = 'peaks_and_plants-graph-bco.html'
peaks_and_plants_dark.save(output_file)

In [18]:
from bs4 import BeautifulSoup

# html_page = peaks_and_plants_dark.get_root().html
# print(html_page)
# len(html_page)
soup = BeautifulSoup(open(output_file), 'html.parser')
script = '<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>'
temp_soup = BeautifulSoup(script)
new_tag = temp_soup.html.script
soup.head.insert(0, new_tag)

my_js = '''
<script>
 var trace1 = {
  x: [-100, 2, 3, +200],
  y: [10, 15, 13, 405],
  mode: 'markers',
  type: 'scatter'
};

var trace2 = {
  x: [2, 3, 4, 5],
  y: [16, 5, 11, 9],
  mode: 'lines',
  type: 'scatter'
};

var trace3 = {
  x: [1, 2, 3, 4],
  y: [12, 9, 15, 12],
  mode: 'lines+markers',
  type: 'scatter'
};

var data = [trace1, trace2, trace3];

Plotly.newPlot('chartContainer', data);

    function gaussian(x, slope, intercept, amplitude, sigma){
        return slope * x + intercept + amplitude / (sigma * ((2 * Math.PI) ** 0.5)) * Math.exp((-(x ** 2)) / (2*(sigma ** 2)));
    }

    function co2Data(data, slope, intercept, amplitude, sigma) {
        console.log('co2Data', slope, intercept, amplitude, sigma);
        var x_tab = [];
        var y_tab = [];
        var y_gaussian = [];
        graphDiv = document.getElementById('chartContainer')
        for (var i = 0; i < data.length; i++) {
            x_tab.push(data[i].distance)
            y_tab.push(data[i].xco2)
            y_gaussian.push(gaussian(data[i].distance, slope, intercept, amplitude, sigma))
        }
        var CO2dataPoints = {
            x: x_tab,
            y: y_tab,
            mode: 'markers',
            type: 'scatter'
        };
        var gaussianDataPoints = {
            x: x_tab,
            y: y_gaussian,
            mode: 'lines',
            type: 'scatter'
        };
        var layout = {
            title: "Km", 
            xaxis: {
                range: [-105, +105]
            },
            yaxis: {
                range: [398, 415]
            }
        };
    var data = [gaussianDataPoints, CO2dataPoints];

        Plotly.react(graphDiv, data, layout)
        console.log('leaving co2Data');
        //console.log(dataPoints)
    }

    function removeData(graphDiv) {
        //Plotly.deleteTraces(graphDiv, 0);
    }
    // Thanks to https://stackoverflow.com/questions/6129145/pass-extra-parameter-to-jquery-getjson-success-callback-function
    function createCallback(slope, intercept, amplitude, sigma) {
       return function(data) {
          co2Data(data, slope, intercept, amplitude, sigma);
          console.log('createCallback', slope, intercept, amplitude, sigma);
          // This reference to the `item` parameter does create a closure on it.
          // However, its scope means that no caller function can change its value.
          // Thus, since we don't change `item` anywhere inside `createCallback`, it
          // will have the value as it was at the time the createCallback function
          // was invoked.
       };
     }

    function plot_data(url, slope, intercept, amplitude, sigma) {
        //console.log('plot_data', slope, intercept, amplitude, sigma);
        graphDiv = document.getElementById('chartContainer')
        removeData(graphDiv);
        
        $.getJSON(url, createCallback(slope, intercept, amplitude, sigma));
        console.log('leaving plot_data');
    }
    plot_data('http://courty.fr/OCO2/peak_data-f_oco2_1808-o_22061-si_2018082505142132.json', 0.0009209859201556104, 400.95202483791405, 130.72568476723046, 13.712969744580016);
</script>'''
new_tag = BeautifulSoup(my_js).html.script
soup.body.insert(0, new_tag)

chart_div = '<div id="chartContainer" style="height: 370px; width: 100%;"></div>'
new_tag = BeautifulSoup(chart_div).html.body.div
soup.body.insert(0, new_tag)

with open("peak_map_with_graph.html", "w", encoding='utf-8') as file:
    file.write(str(soup))

In [ ]:
temp_soup.head.script

In [ ]:
soup.head.insert(3, script)

In [ ]:
soup.body.script